# Replace all "esp32s2-template ..." entries with your sensor name (no whitespace, all lowercase)
#
esphome:
  name: esp32s2-template
  friendly_name: "ESP32S2 Template"
  includes:
    - uart_read_line_sensor_ld2410v3.h
  on_boot:
    priority: -100
    then:
      - script.execute: get_config

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
  logs:
    sensor: INFO # at DEBUG level with uart_target_output = overload!
    binary_sensor: INFO
    text_sensor: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxx"

ota:
  - platform: esphome # uncomment when needed after 2024.6 update
    password: !secret esp32s2-template_ota
    #num_attempts: 3 
    #safe_mode: none

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: 192.168.x.x
  # Manual IP if needed
  #manual_ip: 
    #static_ip: 192.168.x.x
    #gateway: 192.168.x.x
    #subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32s2-template Hotspot"
    password: "xxxxxxxxx"

substitutions:
  #device_name: dev-sensor

web_server:
  port: 80
  version: 2
  include_internal: true
  ota: false

# Workaround for deprecation of custom_components:
# https://github.com/robertklep/esphome-custom-custom_component:
external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]

captive_portal:

uart:
  id: uart_bus
  tx_pin:
    number: GPIO18
  rx_pin:
    number: GPIO33
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

switch:
  - platform: safe_mode
    name: "Restart in Safe Mode"
    id: use_safemode

  - platform: template
    name: "Config Mode"
    id: configmode
    optimistic: true
    # assumed_state: false
    internal: false
    turn_on_action:
      # - switch.turn_off: engineering_mode
      - lambda: 'static_cast<LD2410 *>(ld2410)->setConfigMode(true);'
      - delay: 100ms
      - script.execute: clear_targets
    turn_off_action:
      - lambda: 'static_cast<LD2410 *>(ld2410)->setConfigMode(false);'

  - platform: template
    name: "Show Target Stats"
    id: show_stats
    optimistic: true
    internal: false
    turn_off_action:
      - script.execute: clear_targets

text_sensor:
  - platform: template
    name: "Uptime human"
    id: uptime_human_readable
    icon: mdi:clock-start
    update_interval: 60s
    internal: false

sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 60s
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human_readable
            state: !lambda |-
                      int seconds = round(id(uptime_sensor).raw_state);
                      int days = seconds / (24 * 3600);
                      seconds = seconds % (24 * 3600);
                      int hours = seconds / 3600;
                      seconds = seconds % 3600;
                      int minutes = seconds /  60;
                      seconds = seconds % 60;
                      return (
                        (days ? to_string(days)+"d:" : "00d:") +
                        (hours ? to_string(hours)+"h:" : "00h:") +
                        (minutes ? to_string(minutes)+"m:" : "00m:") +
                        (to_string(seconds)) +"s"
                      ).c_str();

  - platform: custom # Deprecated - currently crashes ESP32
    lambda: |-
      auto uart_component = static_cast<LD2410 *>(ld2410);
      //return {uart_component->movingTargetDistance,uart_component->movingTargetEnergy,uart_component->stillTargetDistance,uart_component->stillTargetEnergy,uart_component->detectDistance};
      return {};
    sensors:

  - platform: template
    name: "Target Moving Distance"
    id: movingTargetDistance
    unit_of_measurement: "cm"
    accuracy_decimals: 0
    internal: false

  - platform: template
    name: "Target Moving Energy"
    id: movingTargetEnergy
    unit_of_measurement: "%"
    accuracy_decimals: 0
    internal: false

  - platform: template
    name: "Target Still Distance"
    id: stillTargetDistance
    unit_of_measurement: "cm"
    accuracy_decimals: 0
    internal: false

  - platform: template
    name: "Target Still Energy"
    id: stillTargetEnergy
    unit_of_measurement: "%"
    accuracy_decimals: 0
    internal: false

  - platform: template
    name: "Distance Detection"
    id: detectDistance
    unit_of_measurement: "cm"
    accuracy_decimals: 0
    internal: false

  - platform: dht
    pin: GPIO9
    temperature:
      name: "Temperature"
      id: temperature
      filters:
        - offset: -1.0
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    humidity:
      name: "Humidity"
      id: humidity
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    update_interval: 15s
    model: DHT11

  - platform: adc
    pin: GPIO3
    name: "Illuminance"
    id: illuminance
    update_interval: '60s'
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return ((x / 10000.0) * -20000000.0) + 1635;
          // KY-018 background: https://community.home-assistant.io/t/126274/11
          // https://community.home-assistant.io/t/126274/17

custom_component:
  - lambda: |-
      return {new LD2410(id(uart_bus))};
    components:
      - id: ld2410

binary_sensor:
  - platform: gpio
    name: "Occupancy"
    id: mmwave_presence_ld2410
    pin: GPIO5
    device_class: occupancy
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_off: mmwave_presence_ld2410
            then:
              - delay: 150ms
              - script.execute: clear_targets

number:
  - platform: template
    name: "Max Distance"
    id: maxconfigDistance
    unit_of_measurement: "m"
    min_value: 0.75
    max_value: 6
    step: 0.75
    mode: slider #default: slider
    update_interval: never
    optimistic: true
    set_action:
      - switch.turn_on: configmode
      - delay: 50ms
      - lambda: |-
          auto uart_component = static_cast<LD2410 *>(ld2410);
          uart_component->setMaxDistancesAndNoneDuration(x/0.75,x/0.75,id(noneDuration).state);
      - delay: 50ms
      - lambda: 'static_cast<LD2410 *>(ld2410)->queryParameters();'
      - delay: 50ms
      - switch.turn_off: configmode

  - platform: template
    name: "Sensitivity T.hold"
    id: allSensitivity
    unit_of_measurement: "%"
    min_value: 10
    max_value: 100
    step: 2 #5
    mode: slider # default: slider
    update_interval: never
    optimistic: true
    set_action:
      - switch.turn_on: configmode
      - delay: 50ms
      - lambda: |-
          auto uart_component = static_cast<LD2410 *>(ld2410);
          uart_component->setAllSensitivity(x);
      - delay: 50ms
      - lambda: 'static_cast<LD2410 *>(ld2410)->queryParameters();'
      - delay: 50ms
      - switch.turn_off: configmode

  - platform: template
    name: "Motion Hold"
    id: noneDuration
    min_value: 0
    # max_value: 32767
    max_value: 200
    unit_of_measurement: "s"
    step: 2
    mode: slider
    update_interval: never
    optimistic: true
    set_action:
      - switch.turn_on: configmode
      - delay: 50ms
      - lambda: |-
          auto uart_component = static_cast<LD2410 *>(ld2410);
          uart_component->setMaxDistancesAndNoneDuration(id(maxconfigDistance).state, id(maxconfigDistance).state, x);
      - delay: 50ms
      - lambda: 'static_cast<LD2410 *>(ld2410)->queryParameters();'
      - delay: 50ms
      - switch.turn_off: configmode

button:
  - platform: restart
    name: "Restart ESP"
    id: restart_esp
    entity_category: diagnostic
    on_press:
      - switch.turn_on: configmode
      - delay: 50ms
      - lambda: 'static_cast<LD2410 *>(ld2410)->factoryReset();'
      - delay: 150ms
      - lambda: 'static_cast<LD2410 *>(ld2410)->reboot();'
      - delay: 150ms

script:
  - id: get_config
    then:
      - switch.turn_on: configmode
      - delay: 500ms
      - lambda: 'static_cast<LD2410 *>(ld2410)->queryParameters();'
      - delay: 500ms
      - switch.turn_off: configmode

  - id: clear_targets
    then:
      - lambda: |-
          //id(hasTarget).publish_state(0);
          //id(hasMovingTarget).publish_state(0);
          //id(hasStillTarget).publish_state(0);
          id(movingTargetDistance).publish_state(0);
          id(movingTargetEnergy).publish_state(0);
          id(stillTargetDistance).publish_state(0);
          id(stillTargetEnergy).publish_state(0);
          id(detectDistance).publish_state(0);
